---
title: "Ivan Estrada - Unit 1"
output: html_document
---

Load relevant packages
```{r}
library(tidyverse)
library(table1)
library(lessR)
```

```{r}
getwd()
setwd("C:/Users/15417/Desktop/H587/Unit1")
```   

Read in data
```{r}
data <- readxl::read_xlsx("BurnData.xlsx")
```

Explore data-set
```{r}
str(data)
data_clean <- data %>%
  mutate(status = recode_factor(status, 
                                '0' = 'Not Infected',
                                '1' = 'Infected',)) %>%
  mutate(newtrt = recode_factor(newtrt,
                                '0' = 'Standard Treatment',
                                '1' = 'New Treatment')) %>%
  mutate(female = recode_factor(female,
                                '0' = 'Male',
                                '1' = 'Female')) %>%
  mutate(white = recode_factor(white,
                               '0' = 'Non-White Patients',
                               '1' = 'White Patients')) %>%
  mutate(burntype = recode_factor(burntype,
                                '1' = 'Checmical Burn',
                                '2' = 'Scald',
                                '3' = 'Electric',
                                '4' = 'Flame'))
label(data_clean$time) <- "Time to infection or release from burn ward"
label(data_clean$status) <- "Infection status"
label(data_clean$newtrt) <- "Treatment Status"
label(data_clean$female) <- "Sex"
label(data_clean$white) <- "Race"
label(data_clean$saburned) <- "Percentage of total body surface area burned"
label(data_clean$burntype) <- "Burn type"
```
Table 1 
```{r}
#table1 stored to object for use
st.table<-table1(~ newtrt + status + time + female + white + saburned + burntype |newtrt,
                      data = data_clean, overall = "Total", 
                      topclass = "Rtable1-times Rtable1-zebra Rtable1-shade")
#clean table1                      
df<-as.data.frame(st.table) #change from html table to dataframe
df[rbind(c(3,3),c(3,4),c(4,3),c(4,4))]<-NA # Set NA's # Set NAs
df <- df[-c(2,5,8,11,14,17,21),] # Remove header rows
rownames(df)<-c() #Remove numbered rownames

#Recreate table
library(kableExtra)
kable(df) %>% 
#table style
  kable_styling(html_font = "Arial","striped",full_width=F, font_size = 11) %>% 
  row_spec(0,background="whitesmoke",bold=T) %>% 
  row_spec(1,bold=T, extra_css = "border-bottom: 1px solid" ) %>%  #bold header
  #set Sub headers
  pack_rows(group_label = "Treatment Status", start_row = 2, end_row = 3) %>%  
  pack_rows(group_label = "Infection Status", start_row = 4, end_row = 5) %>% 
  pack_rows(group_label = "Time to infection or release from burn ward", start_row = 6, end_row = 7) %>% 
  pack_rows(group_label = "Sex", start_row = 8, end_row = 9) %>% 
  pack_rows(group_label = "Race", start_row = 10, end_row = 11) %>% 
  pack_rows(group_label = "Surface area burned (percent)", start_row = 12, end_row = 13) %>% 
  pack_rows(group_label = "Burn type", start_row = 14, end_row = 17)

```














